-- GENERATED by `npm run divisions` from contest.config.ts → competition.divisions.
-- Do not edit by hand. Apply it after the migrations, and again whenever divisions change:
--   Supabase → SQL Editor → paste this file → Run   (or: psql "$DATABASE_URL" -f supabase/divisions.sql)
-- It refuses to remove a division that registrations, scores or the run order still use.

begin;

insert into public.contest_divisions
  (code, name, scoring_format, tech_cap, eval_cap, allow_negative, stop_points, discard_points, detach_points, manual_max, has_music, sort_order)
values
  ('1A', '1A — Single String', 'freestyle', 60, 10, true, 1, 3, 5, null, true, 1),
  ('X', 'X Division', 'freestyle', 60, 10, true, 1, 3, 5, null, true, 2),
  ('SBJ', 'Sport / Beginner / Junior', 'freestyle', 20, 20, false, 0, 0, 0, null, true, 3)
on conflict (code) do update set
  name = excluded.name, scoring_format = excluded.scoring_format, tech_cap = excluded.tech_cap,
  eval_cap = excluded.eval_cap, allow_negative = excluded.allow_negative, stop_points = excluded.stop_points,
  discard_points = excluded.discard_points, detach_points = excluded.detach_points,
  manual_max = excluded.manual_max, has_music = excluded.has_music, sort_order = excluded.sort_order,
  updated_at = now();

insert into public.contest_division_styles (division_code, code, label, multiplier, sort_order)
values
  ('X', '2A', '2A — Looping', 1.4, 1),
  ('X', '3A', '3A — Two-Handed String', 1.5, 2),
  ('X', '4A', '4A — Offstring', 1.3, 3),
  ('X', '5A', '5A — Freehand', 1.6, 4)
on conflict (division_code, code) do update set
  label = excluded.label, multiplier = excluded.multiplier, sort_order = excluded.sort_order;

delete from public.contest_division_styles
 where (division_code, code) not in (('X', '2A'), ('X', '3A'), ('X', '4A'), ('X', '5A'));

delete from public.contest_divisions where code not in ('1A', 'X', 'SBJ');

commit;
